- hosts: apilbs
  gather_facts: true
  tasks:
    name: Configure Admin
    shell: '{{ item }}'
    with_items:
      - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true --server=https://{{inventory_hostname}}.kubernetes.loc
      - kubectl config set-credentials admin --client-certificate=admin.pem --client-key=admin-key.pem
      - kubectl config set-context kubernetes-the-hard-way --cluster=kubernetes-the-hard-way --user=admin
      - kubectl config use-context kubernetes-the-hard-way
      - kubectl create clusterrolebinding apiserver-kubelet-admin --user=kubernetes --clusterrole=system:kubelet-api-admin
      - kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE=10.200.0.0/16"
    args:
      chdir: "{{ userHomeFolder }}"
    register: createCaAdminCerts
    tags: createCaAdminCerts

