---
- name: Copy certificates to the Worker nodes
  copy:
    src: "{{userHomeFolder}}/{{item}}"
    dest: "{{userHomeFolder}}/"
  with_items:
    - ca.pem 
    - "{{inventory_hostname}}.kubernetes.loc-key.pem"
    - "{{inventory_hostname}}.kubernetes.loc.pem"
  register: copyCertsToWorkers
  tags: copyCertsToWorkers
  when: installPacks is success and createKubeFolders is success

- name: Copy KubeConfig to the Worker nodes
  copy:
    src: "{{userHomeFolder}}/{{item}}"
    dest: "{{userHomeFolder}}/"
  with_items:
    - "{{inventory_hostname}}.kubernetes.loc.kubeconfig"
    - kube-proxy.kubeconfig
  register: copyConfigsToWorkers
  tags: copyConfigsToWorkers
  when: installPacks is success and createKubeFolders is success

- name: Unarchive Kuberenetes Binary files
  unarchive:
    src: "{{ archivesFolder }}/{{ item.src }}"
    dest: "{{ item.dst }}/"
  with_items:
    - { src: 'kubelet.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'kubectl.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'kube-proxy.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'runc.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'runsc.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'crictl.tar.bz2', dst: '{{ binaryDestination }}' }
    - { src: 'cniplugins.tar.bz2', dst: '/opt/cni/bin' }
    - { src: 'containerd.tar.bz2', dst: '/bin' }
  tags:
    - unarchiveKubernetesFiles
  register: unarchiveKubernetesFiles
  when: copyCertsToWorkers is success and copyConfigsToWorkers is success

...
